# ----------
#  サービス名
# ----------
service: fsaito-service

# -------------
#  バージョン
# -------------
frameworkVersion: '2'

# ----------------------
#  各種設定用 (環境設定とか)
# ----------------------
custom:
  defaultStage: local
  defaultRegion: ap-northeast-1
  defaultEnv: local
  env: ${env:NODE_ENV, self:custom.defaultEnv}

# ----------
#  AWSの設定
# ----------
provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  profile: serverless-sandbox
  environment:
    DYNAMODB_TABLE: ${self:service}-table
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query #条件検索
        - dynamodb:Scan #全件取得
        - dynamodb:GetItem #一件取得
        - dynamodb:PutItem #一件登録
        - dynamodb:UpdateItem #修正
        - dynamodb:DeleteItem #削除
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}*"

# ----------------------------
#  Lambda設定
# ----------------------------

functions:
  sample01:
    handler: src/functions/sample01/handler.sample01
    events:
      - http:
          path: call
          method: get
  sample02:
    handler: src/functions/sample02/handler.sample02
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - DynamodbQueues
              - StreamArn


# ----------------------------
# DynamoDBの設定
# ----------------------------

resources:
  Resources:
    DynamodbQueues:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}-queues
        AttributeDefinitions:
          - AttributeName: created_at
            AttributeType: S
          - AttributeName: code
            AttributeType: S
        KeySchema:
          - AttributeName: created_at
            KeyType: HASH
          - AttributeName: code
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST # オンデマンドキャパシティーモード
        StreamSpecification:
            StreamViewType: NEW_IMAGE